### ISSUE TITLE
Support Intellij 2021.2

### ISSUE THREAD

**Issue by CXwudi** [nbadal/ktlint-intellij-plugin#109]
Just updated my Intellij to 2021.2 today and I got this
![image](https://user-images.githubusercontent.com/17377423/127205343-78c4bc77-fc0d-400c-8658-4109f6d780ea.png)

**Comment by ssamayoa** [comment]
Same here :(

**Comment by nbadal** [comment]
Support added in 0.8.0, should be available soon!
