### ISSUE TITLE
0.8.1 cannot be installed with IJ 2021.3

### ISSUE THREAD

**Issue by juergenzimmermann** [nbadal/ktlint-intellij-plugin#132]
The ktlint plugin cannot be installed on IntelliJ 2021.3. It would be nice if you could support the new IJ release.

**Comment by juergenzimmermann** [comment]
@nbadal Maybe you can just extend the compatibility range as in https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/issues/494

**Comment by nbadal** [comment]
Thanks for the heads up! I'm curious why my nightly version check didn't open a PR for this, I'll investigate!

**Comment by nbadal** [comment]
Ah, 213 is still in EAP! Thoughts on EAP so far are captured in #36

**Comment by CXwudi** [comment]
Heads up, 2021.3 is public available now
