### ISSUE TITLE
misconfigures the import order when using Mockito

### ISSUE THREAD

**Issue by shapan1** [nbadal/ktlint-intellij-plugin#148]
Found a bug today where the lexicographical order is unable to correct order Mockito import for when containing  the character `
```
import org.mockito.Mockito.`when`
import org.mockito.Mockito.after
import org.mockito.Mockito.any
import org.mockito.Mockito.doReturn
import org.mockito.Mockito.doThrow
```
This is the correct order, however ktlint shows this as an error and then after running it. The import are incorrectly ordered to 
```
import org.mockito.Mockito.after
import org.mockito.Mockito.any
import org.mockito.Mockito.doReturn
import org.mockito.Mockito.doThrow
import org.mockito.Mockito.`when`
```
due to the ` character

**Comment by nbadal** [comment]
This seems to be the intended behavior, it was changed within ktlint itself here: https://github.com/pinterest/ktlint/issues/1106

The fact that it doesn't match up with the IDE's sorting order is either a ktlint bug, or a bug with the Kotlin plugin as noted in the link above.

**Comment by nbadal** [comment]
Out of my own curiosity, I have submitted a change to the JetBrains Kotlin plugin to match this ordering, and it will eventually be released in an update 😁
