### ISSUE TITLE
Support Intellij 2021.3

### ISSUE THREAD

**Issue by huehnerlady** [nbadal/ktlint-intellij-plugin#152]
As Intellij 2021.3 is now released would be great to get this plugin supported again :) 

_Originally posted by @CXwudi in https://github.com/nbadal/ktlint-intellij-plugin/issues/132#issuecomment-983027521_

**Comment by huehnerlady** [comment]
@nbadal could you maybe give an update here when this will be available?

**Comment by nbadal** [comment]
Should have this up in the next day or so! Dealing with some commit signing issues on my personal dev machine, so I may just make the changes manually on Github tonight 😬

**Comment by leninmedeiros** [comment]
@nbadal any updates on that? I am really looking forward to be using ktlint again here as I recently updated my IJ version to 2021.3 :D

**Comment by nbadal** [comment]
0.8.2 is published on my end as of tonight! As soon as Jetbrains approves, it should be available. I appreciate everyone's patience 😁 

Hoping to start integrating during EAP so that it's available immediately for upcoming versions.

**Comment by Jolley71717** [comment]
> 0.8.2 is published on my end as of tonight! As soon as Jetbrains approves, it should be available. I appreciate everyone's patience 😁
> 
> Hoping to start integrating during EAP so that it's available immediately for upcoming versions.

A bit off topic, but is there anywhere we can track the status of this?
I'm interested in the process that Intellij goes through for approving plugins, and I'm especially interested in this plugin.

**Comment by nbadal** [comment]
@Jolley71717  If you set up notifications for releases on this repo, you'll see when I submit to JetBrains. They usually review within a business day or two 😄 
![image](https://user-images.githubusercontent.com/394812/146987225-df1e3261-c0ec-41c3-b386-1294f31d8608.png)

Also, I have a job set up to automatically open PRs for new IDE versions that are published to EAP.

(+ Closing now that the update has been published)
