### ISSUE TITLE
Intellij version to 203.*

### ISSUE THREAD

**Issue by thiagodsti** [nbadal/ktlint-intellij-plugin#16]
Can you increase the version of intellij to 203.*

I've tried to open a PR for you, but looks like we are not allowed.
Thanks

**Comment by r6e** [comment]
Opened #17 to address this.

**Comment by tekener** [comment]
Hi, 2020.3 is out now and it would be nice to have ktlint again... 😁

**Comment by nbadal** [comment]
Sorry for the delay folks! Honestly wasn't expecting so much engagement, I guess this is my first proper open source github issue 😂  – I'll address this today!

+ Thanks @r6e!

**Comment by nbadal** [comment]
Also fixed my email notification settings so I don't miss another discussion 👀  thanks all

0.6.0 will be submitted later today with `203.*` support!

**Comment by nbadal** [comment]
v0.6.0 has been submitted, and is available immediately via GitHub releases. Closing for now, thanks everyone!
