### ISSUE TITLE
0.8.2 cannot be installed with IJ 2022.1 EAP

### ISSUE THREAD

**Issue by juergenzimmermann** [nbadal/ktlint-intellij-plugin#171]
The ktlint plugin cannot be installed on IntelliJ 2022.1. It would be nice if you could support the new IJ EAP release.

Maybe you can just extend the compatibility range as in https://github.com/nbadal/ktlint-intellij-plugin/issues/132.

**Comment by rbleuse** [comment]
According to [this comment](https://github.com/nbadal/ktlint-intellij-plugin/issues/152#issuecomment-999041053) there's a Github action which checks new IntelliJ versions and create a PR to support new version.
The PR has been created https://github.com/nbadal/ktlint-intellij-plugin/pull/170, we just have to wait for it to be checked and merged

**Comment by nbadal** [comment]
Fixed the issue in the PR + script, and merged 221.* support! Should be ready in the next release in the next few days 😁

**Comment by nbadal** [comment]
And now released 😁
