### ISSUE TITLE
0.9.0 cannot be installed with IJ2022.2 EAP

### ISSUE THREAD

**Issue by juergenzimmermann** [nbadal/ktlint-intellij-plugin#203]
The ktlint plugin cannot be installed on the fresh available IntelliJ 2022.2 EAP. It would be nice if you could support it.
Maybe you can just extend the compatibility range.

**Comment by nbadal** [comment]
@juergenzimmermann thank you again again for the heads up! I'll add support and look into why the PR wasn't auto-created 😅

**Comment by nbadal** [comment]
Will be supported in `0.9.1` 😁
