### ISSUE TITLE
Feature Request: allow maven coordinates for --ruleSet

### ISSUE THREAD

**Issue by kenyee** [nbadal/ktlint-intellij-plugin#207]
The ktlint Gradle plugin allows using maven coordinates.

Would be nice if the IDE plugin could as well.

**Comment by nbadal** [comment]
That's an interesting suggestion! The Gradle plugin gets that functionality fairly cheaply since Gradle has direct maven access etc.

For that to work in the IDE, the maven resolution would have to happen at runtime without any of the supporting Gradle scaffolding.

Not impossible, but would definitely require some deeper investigation 😁

**Comment by nbadal** [comment]
Note: This runtime maven functionality would be implemented very similarly to #35 which is also a ktlint Gradle plugin feature

**Comment by kenyee** [comment]
You can use the Aether library (https://github.com/sonatype/sonatype-aether) to grab maven artifacts though it's super ancient.  Probably a similar technique could be used to allow this plugin to support multiple ktlint plugins...download jars, add to classpath, and then use that ktlint version.

**Comment by nbadal** [comment]
@kenyee Thanks for the tip! 😁 Will definitely look into that and see if:
 - it could work
 - if there's a more modern take on that mechanism
 - how it would effect the size/resource usage of the plugin

**Comment by paul-dingemans** [comment]
Not all rulesets can be downloaded via maven coordinates. For example, the [compose rules can only be used when downloading the fat jar from the release page of the project](https://github.com/mrmans0n/compose-rules/releases/tag/v0.3.2)). As it is not something which needs to be done daily, it is better to leave the responsibility for downloading and verifying to be handled by the developer.

**Comment by paul-dingemans** [comment]
Next version (0.22.x) of plugin supports ktlint versions 0.50.0, 1.0.1, 1.1.1 and 1.2.1. Downloading of rulesets based on maven coordinates will not be supported.
