### ISSUE TITLE
Love this plugin - how do I share supression rules across the team?

### ISSUE THREAD

**Issue by snijsure** [nbadal/ktlint-intellij-plugin#226]
I have been using this plugin and absolutely love it.

When it flags some rules that we don't care of in our project, I am suppressing them for the project, that works. 

Where are those suppression rules stored, can they be shared across team members?

**Comment by nbadal** [comment]
@snijsure Glad you're enjoying it! You should probably utilize the `.editorconfig` file to do shared configuration.

Docs: https://pinterest.github.io/ktlint/faq/#how-do-i-globally-disable-a-rule

**Comment by paul-dingemans** [comment]
Using the `.editorconfig` and saving this file to VCS is indeed the way to go to share the same configuration between team members.
