### ISSUE TITLE
0.10.0 cannot be installed with IJ 2022.3 EAP

### ISSUE THREAD

**Issue by juergenzimmermann** [nbadal/ktlint-intellij-plugin#234]
The ktlint plugin 0.10.0 cannot be installed on IntelliJ 2022.3 EAP. It would be nice if you could support the new IJ release.

**Comment by nbadal** [comment]
Thanks for the heads up! It seems I break my IDE update automation every cycle right before a new version drops. Fixing now!

**Comment by nbadal** [comment]
Fixed script, #235 opened 😁

**Comment by gerrytan** [comment]
Same problem with IJ 2022.2.1, it installs, then lingers in disabled state. The enable checkbox is greyed out. I hope the same fix applies.
