### ISSUE TITLE
disabled_rules in .editorconfig were deprecated

### ISSUE THREAD

**Issue by vojkny** [nbadal/ktlint-intellij-plugin#238]
Within new ktlint, these should be named `ktlint_disabled_rules`, however it seems that these are ignored by the plugin?

**Comment by paul-dingemans** [comment]
Not relevant anymore with (upcoming) `0.20.0` version of plugin as setting for disabled rules is removed. With that version rules can only be disabled by modifying the `.editorconfig`.
