### ISSUE TITLE
Provide an option to run ktlint all project files or package.

### ISSUE THREAD

**Issue by sureshg** [nbadal/ktlint-intellij-plugin#24]
Thanks for this awesome plugin, much appreciated. It would be really helpful to have an option to run the lint task for all files in a project or a package instead of doing it file by file.

**Comment by nbadal** [comment]
This should be possible, in theory! We currently use an Annotator, but we could switch to using the [Inspection system within the IDE](https://jetbrains.org/intellij/sdk/docs/reference_guide/custom_language_support/code_inspections_and_intentions.html).

This requires a bit more configuration, but I'll look back into it soon 😄

**Comment by pauldingemans** [comment]
I would also like to have an "analyze all" functionality. I have some doubts whether the default inspection system if the best place to go. The amount of inspections results is usually already overwhelming. I would prefer something similar to the "Sonarlint" plugin, e.g.:
* A separate tool window for ktlint offering functionalities like:
** A toolbar containing actions:
*** running ktlint on the current file
*** running ktlint on all files in the changeset
*** running ktlint on all files in the project
*** A toggle for enabling/disabling autocorrect mode
** A result tab:
*** ktlint violations (all violations when autocorrect is disabled / unsolved violations when autocorrect is enabled)
*** violations can be clicked and result in navigating to the source file / line / position indicated by ktlint
** A log tab containing the raw ktlint output
* Menu items in the "Analyze" menu for options:
** running ktlint on all files in the changeset
** running ktlint on all files in the project

@nbadal If this project is open to contributions and support approach above I am willing to contribute to it.

**Comment by nbadal** [comment]
@pauldingemans Definitely open to contributions! A panel like that should definitely be feasible, though the "run ktlint on project/scope" action would probably be the quickest way to address OP's use case

**Comment by paul-dingemans** [comment]
Great, I will start working on that. I was actually planning to create my own ktlint plugin for this functionality just before I discovered yours. It would be much nicer to combine both. As you might notice, this remark is coming from a slightly different github account. I accidentally used my old account in the previous remark ;-)

**Comment by nbadal** [comment]
Added a right-click option to the Project window that will address the majority of the cases mentioned here 🙂
