### ISSUE TITLE
Alert user when ruleset can not be loaded

### ISSUE THREAD

**Issue by nbadal** [nbadal/ktlint-intellij-plugin#243]
For missing files / JARs without rules / etc on the config page, we should show a warning

**Comment by paul-dingemans** [comment]
In upcoming release, a warning about a custom jar without acceptable ruleset provider will be shown as balloon. I could not find a way to display a warning inside the settings dialog.

Baseline loader swallows any exception when the file is invalid and prints a log message (see https://github.com/pinterest/ktlint/issues/2344).
