### ISSUE TITLE
incompatible in 223 build version

### ISSUE THREAD

**Issue by hanqyu** [nbadal/ktlint-intellij-plugin#249]
intellij 2022.3 version just got released. But it seems that this plugin is not compatible.

**Comment by ssamayoa** [comment]
"Incompatible: requires IDE build 222.* or earlier"
:(

**Comment by nbadal** [comment]
v0.11.0 has been sent to Jetbrains which includes 223 support :)

**Comment by Darkilen** [comment]
You added support for 2022.3.1 RC version ([build 223.8214.16](https://youtrack.jetbrains.com/articles/IDEA-A-2100661413/IntelliJ-IDEA-2022.3.1-Preview-223.8214.16-build-Release-Notes)), not 2022.3 ([build 223.7571.182](https://youtrack.jetbrains.com/articles/IDEA-A-2100661406/IntelliJ-IDEA-2022.3-223.7571.182-build-Release-Notes)) nor 2022.3.1 ([build 223.8214.52](https://youtrack.jetbrains.com/articles/IDEA-A-2100661418/IntelliJ-IDEA-2022.3.1-223.8214.52-build-Release-Notes)).

Commit : https://github.com/nbadal/ktlint-intellij-plugin/commit/cfdc7f07584831f644f3ce60cbbac5992d938943#diff-3d103fc7c312a3e136f88e81cef592424b8af2464c468116545c4d22d6edcf19

**Comment by nbadal** [comment]
@Darkilen that build version is just the IDE version that the validation plugin runs against, `pluginUntilBuild` is the important field there 😁
