### ISSUE TITLE
Dude, i you can't maintain your plugin, delegate it to someone.

### ISSUE THREAD

**Issue by BumbrT** [nbadal/ktlint-intellij-plugin#251]
Can't update idea until you publish proper version of this plugin. Real pain

**Comment by vincentrolfs** [comment]
I  really can't believe your comment. If you need it so badly for production, fork the repo and maintain it yourself. The creator owes you nothing. We are lucky they wrote this plugin at all.

**Comment by BumbrT** [comment]
I've tried to fork it and compile plugin for myself. Ended up with hanged plugin in idea. For sure there are a lot of people who want to contribute and build it for new idea release, as you can find PRs with fixes. But for now it's easier to just launch `ktlint --format`, instead of fighting with this repo.

**Comment by FyiurAmron** [comment]
FWIW, simply giving some people with good past OSS collaboration history elevated access on this repo would be enough. @nbadal could retain the ownership while delegating the chores. 1 person is always too little, mainly due to [bus factor](https://en.wikipedia.org/wiki/Bus_factor) etc.

**Comment by nbadal** [comment]
@FyiurAmron hit the nail on the nead, #230 is a substantial lift that's taken nearly all of my focus. I did just get some resourcing allocated for this at my day job so hoping to address the larger refactors this coming month. Most folks seem to be upset about IDE upgrades, so I'll be prioritizing getting that out first. 

As for pulling in additional contributors, I haven't seen a single pull request offering to assist... Lets cross that bridge first folks
