### ISSUE TITLE
RFE: add quick fix for just formatting specific issue at hand

### ISSUE THREAD

**Issue by grexe** [nbadal/ktlint-intellij-plugin#252]
when ktlint finds an issue, I can either:
* ignore it
* format the *entire file*
* manually fix the issue at hand

This is quite inflexible, as most often, I don't want to go to either extreme, but just fix the issue at hand, as is common in IntelliJ inspections and quick fix actions.
It would be great if ktlint followed this pattern, too.

**Comment by nbadal** [comment]
My plugin is basically limited to the same actions that the command line `ktlint` can take, unfortunately. This would require a feature request at the `ktlint` API level to expose a way to format individual errors, so technically possible!

**Comment by paul-dingemans** [comment]
As maintainer of Ktlint, I have no intention to make this possible as it would be a considerable architectural change from which only the intellij plugin will benefit. Also it does conflict with the new "strategy" for the plugin. In this new strategy the autocorrect mode of Ktlint is followed and all errors which can be fixed automatically will be fixed. Developers should not spend time on manually fixing (or preventing of autocorrect fixes) from violation when possible.
