### ISSUE TITLE
ktlint reformating does not show up as an intellij on save action

### ISSUE THREAD

**Issue by paulstanila-doctari** [nbadal/ktlint-intellij-plugin#267]
As the title says, I've installed the plugin and played with it for a bit, everything seems to work ok (there were a couple of errors at first which led to the plugin crashing, but I didn't take a screenshot of them) , but the "on save action" does not appear to be there. I saw that there was a recent feature about this and that it should work. I've tried invalidating the caches a couple of times, but that didn't fix anything. Here are some screenshots:

![onSaveActions](https://user-images.githubusercontent.com/117450260/212692652-c136e3fb-0921-4b19-ae8c-2bc304eece81.png)
![pluginIsEnabled](https://user-images.githubusercontent.com/117450260/212693162-7a862544-3157-44c5-9bfc-f625a088a9f1.png)
![intellijVersion](https://user-images.githubusercontent.com/117450260/212693512-54cf0cfe-32a0-4b9e-8ecd-5b05ed533f70.png)

**Comment by paul-dingemans** [comment]
Can not be reproduced. Action is being showed (at least in upcoming release; I did not check whether it was not working in older published releases).
