### ISSUE TITLE
Can you publish 0.12.0?

### ISSUE THREAD

**Issue by bandersongit** [nbadal/ktlint-intellij-plugin#271]
I saw that you recently merged support for 0.48 and bumped the version to 0.12, however it doesn't yet appear to be available. My org just upgraded the ktlint version and I've unfortunately had to disable this plugin until it gets updated :(

**Comment by gschulze** [comment]
I would also be interested in an imminent release. Apparently, Ktlint has changed trailing commas to be mandatory starting with version 0.48.x, which is currently inconsistent with the behavior of the plugin.

**Comment by nbadal** [comment]
This version is now submitted to Jetbrains! Also bumped up to 0.48.2, and added a new IDE version support so wanted to do a fair amount of testing 😅 definitely gets more difficult as ktlint starts to have significantly more API churn

**Comment by gschulze** [comment]
Thank you very much, looking forward to trying it out!

**Comment by bandersongit** [comment]
Same! I don't know if it's possible, but allowing the user to select a version/specify a path to a locally installed ktlint might allow you to not need to release at the same cadence as ktlint

**Comment by gschulze** [comment]
@bandersongit Good idea, I was thinking the same when I discovered the versions of plugin and CLI tool were out of sync.
