### ISSUE TITLE
.editorconfig override path

### ISSUE THREAD

**Issue by mezpahlan** [nbadal/ktlint-intellij-plugin#28]
Hi there

Great plugin, our team loves using it! 

I recently upgraded to 0.7.0 and started to notice that previously acceptable kotlin files were now marked with ktlint errors. Specifically the line length error. On closer inspection it seemed to be reporting the line length and import ordering as the default ktlint values and not the values that we have set in our `.editorconfig` file.

I don't remember having to manually configure the editorconfig file in previous versions of the plugin but as a workaround I added the folder that contains this file to the `.editorconfig override path` in the settings menu and that worked. 

The location of our editorconfig hasn't changed ever and has always been in the root of the project.

```
android
  | app
    | build.gradle
  | settings.gradle
  | gradlew
  | build.gradle
  | .editorconfig
```

I'm running Windows if that matters.

**Comment by phanimahesh** [comment]
Can confirm that the editor config at project root is not being picked up. Setting override works, though. Multi module maven project on linux.

**Comment by nbadal** [comment]
Thanks for flagging this! I'll take a look today 😄 

@phanimahesh by chance - did this issue also arise with 0.7.0 specifically for you? Or has it always been the case?

**Comment by nbadal** [comment]
Fix added to 0.7.1 😀

**Comment by phanimahesh** [comment]
I installed the plugin recently and discovered the issue. Not sure if it always existed or was a regression.

**Comment by nbadal** [comment]
Great, just wanted to make sure it was the same cause! 0.7.1 should be rolling out shortly

**Comment by mezpahlan** [comment]
Hi @nbadal mega thanks for the quick patch! I received the update today and tested it out by removing the workaround I mentioned above. Seemed fine for the day of use I had. I didn't restart the IDE in that time but...... I'm assuming that doesn't matter.

Cheers again.
