### ISSUE TITLE
Add support for Gradle version catalog to determine ktlint version

### ISSUE THREAD

**Issue by ZakTaccardi** [nbadal/ktlint-intellij-plugin#283]
Would love to be able to programmatically set our `ktlint` version based on a value in our `dependencies.toml` file ([version catalog](https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog))

**Comment by paul-dingemans** [comment]
Closing. Configuration of the plugin should not be mixed with configuration of other build tools. It would also introduce complexity in case the plugin would not be used with a Gradle build.
