### ISSUE TITLE
Upgrade to ktlint 1.0.0

### ISSUE THREAD

**Issue by cdavie-artium** [nbadal/ktlint-intellij-plugin#306]
https://github.com/pinterest/ktlint/releases/tag/0.49.0

**Comment by nbadal** [comment]
Working on implementing the breaking changes 😁 hopefully done soon!

**Comment by Kantis** [comment]
Might as well go straight to 0.50.0 now, right? 🙂

**Comment by nbadal** [comment]
First commit working towards this is now up!

**Comment by paul-dingemans** [comment]
Plugin version `0.20` is updated to ktlint `1.0.0`. Upgrade to `1.0.1` will follow soonish.

**Comment by nilsschmidthamburg** [comment]
Hi @nbadal,

Thank you for providing support for version 1.0.0! Your efforts are highly appreciated. However, it seems that the new version is not yet available in IntelliJ. Is there anything that still needs to be done? If so, please let me know if there are simple tasks where we could assist you.

Best regards,
Nils

**Comment by paul-dingemans** [comment]
Currently, a prerelease is available https://github.com/nbadal/ktlint-intellij-plugin/releases/tag/vunspecified. Official release follows asap.
