### ISSUE TITLE
Rule "Wrapping the expression body of a function" does not work

### ISSUE THREAD

**Issue by TribuneX** [nbadal/ktlint-intellij-plugin#314]
I try to use the rule [wrapping-the-expression-body-of-a-function](https://pinterest.github.io/ktlint/0.49.1/rules/configuration-ktlint/#wrapping-the-expression-body-of-a-function) within my `.editorconfig`, but it does not seem to be evaluated by the plugin.

Relevant parts in my `.editorconfig`:

```
[{*.kt,*.kts}]
ktlint_standard_function-signature = enabled
ktlint_function_signature_body_expression_wrapping = always
...
```

the ktlint commandline tool correctly add line-breaks to my function signatures, but the IDE plugin does not. Any idea what's wrong? I do not want to enable all experimental rules with the setting `Use experimental rules (--experimental)`.

**Comment by nbadal** [comment]
@TribuneX are you setting your .editorconfig in the project ktlint settings?

**Comment by paul-dingemans** [comment]
@TribuneX Can you enclose a code sample which reproduces this problem? It might very well be that you use a new version of Ktlint CLI compared to the `0.48` version that is used by the plugin.

**Comment by paul-dingemans** [comment]
Clsoed, due to no response. Please feel free to reopen after supplying requested information.

**Comment by TribuneX** [comment]
I can still reproduce it with the following lines of code and ktlint 1.0.1:

```kotlin
// no format
fun someFunction(a: Any, b: Any): String = "some-result".uppercase()
```

```kotlin
// ktlint --format
fun someFunction(
    a: Any,
    b: Any,
): String =
    "some-result".uppercase()
```

I am still using the following `.editorconfig`:

```
[{*.kt,*.kts}]
ktlint_standard_function-signature = enabled
ktlint_function_signature_body_expression_wrapping = always
```

**Comment by paul-dingemans** [comment]
If your complaint is that the plugin does not format the code then that is correct. The plugin still uses Ktlint 0.48 instead of 1.0.1.

I am working on updating the plugin.
