### ISSUE TITLE
Please create a new release to support IntelliJ 232

### ISSUE THREAD

**Issue by dfirsht** [nbadal/ktlint-intellij-plugin#328]
Hello!

Can we please add support for the latest version of IntelliJ (2023.2)?

Thanks!

**Comment by ikamil** [comment]
will you add?

**Comment by dfirsht** [comment]
Yeah I saw that. Managed to compile and get working in 232 after bumping to `id("org.jetbrains.intellij") version "1.15.0"` and removing the rollbar code

**Comment by IvanPizhenko** [comment]
Any timeline for this?

**Comment by janhoeve** [comment]
> Any timeline for this?

I'm curious as well since for us it's pretty mandatory to switch to the latest IntelliJ version.
Tagging the maintainer @nbadal :)

**Comment by Spikhalskiy** [comment]
Looks like this is not getting any attention from the maintainer. 
I made a build that works with the new Idea that can be installed using 
Files -> Settings -> Plugins -> <gear icon> -> Install Plugin From Disk
Zip file with modified plugin: https://raw.githubusercontent.com/Spikhalskiy/ktlint-intellij-plugin/build-hack/plugin/build/distributions/ktlint-0.13.0-SNAPSHOT.zip

If you want to build your own plugin not trusting (rightfully) random zip files, the hacked (without error reporter) working sources are here https://github.com/Spikhalskiy/ktlint-intellij-plugin/commits/build-hack, the final zip will be located in 'plugin/build/distributions/' after running './gradlew build'

**Comment by nbadal** [comment]
v0.13.0 is now released 🎉 

As a sole maintainer (especially one whose job doesn't touch kotlin / ktlint anymore), finding time for this can be difficult. Always open to additional maintainers, please feel free to submit a pull request if you'd like to contribute or help out!

**Comment by mattelacchiato** [comment]
I would like to contribute and help maintaining. 

I've previously already submitted a [PR](https://github.com/nbadal/ktlint-intellij-plugin/pull/230) in the past, wich became obsolete over time waiting for approval..
