### ISSUE TITLE
Add action to disable rules via editorconfig

### ISSUE THREAD

**Issue by nbadal** [nbadal/ktlint-intellij-plugin#340]
This seems to be the new preferred method of disabling rules

**Comment by paul-dingemans** [comment]
Rules indeed need to be disabled via `.editorconfig` properties. The plugin should not store its own state to pass down to KtLint. In case ktlint is also invoked in the build pipeline, this might result in different behavior in the IntelliJ IDEA versus the build pipeline. If both use the same `.editorconfig` for configuring ktlint, both will respond identical.
