### ISSUE TITLE
Please support ktlint 1.0.0

### ISSUE THREAD

**Issue by szedelenyi** [nbadal/ktlint-intellij-plugin#347]
ktlint 1.0.0 has been released on the 5th of September and it has some breaking changes regarding conventions. Please add support for it.

**Comment by szedelenyi** [comment]
I see [you are already working on it](https://github.com/nbadal/ktlint-intellij-plugin/commit/d8d0cf3d11e352ee19f43771d48732e7cbc6136f). Thank you <3

**Comment by nbadal** [comment]
@szedelenyi Yep! Feel free to download a manual zip if 1.0.0 support is critical. I'm working on ironing out the last few features and configuration options 😁

**Comment by nbadal** [comment]
Closing as a dupe of #306 which I'll close once I submit the update to Jetbrains
