### ISSUE TITLE
Please do not make the plugin aggressive by default or revert it

### ISSUE THREAD

**Issue by Vampire** [nbadal/ktlint-intellij-plugin#356]
@paul-dingemans said in #308 that this plugin will become much more aggressive on next release and automatically reformat on every save and on every reformat.

This would mean I will immediately uninstall the plugin and recommend everybody to remove it from their IDE, maybe even require to disable it for contributors. That behavior is way too aggressive except if I opted in. I would also never website the built-in format-on-save. I am the developer and decide when I want to format. I often have projects open where for example no trailing commas are used, which imho is good, and where also no ktlint is used anywhere. The IntelliJ plugin nevertheless shows errors for that, as it just always is active if not disabled manually or an `.editorconfig` added which tells ktlint to behave properly.

As long as it only showed an error, I could accept that. But if it now starts to auto correct theses errors and thus auto-uglifies any project I contribute to, or any project someone contributing to me that uses the plugin, that is imho unacceptable behavior.

Even if I invoke the IntelliJ formatter I don't necessarily want ktlint to interfere, as I might like IntelliJ result better. Even if you consider that bikeshedding, it isn't. A project can for example have as anti-bikeshedding rule to use the IJ formatter, but anyone just having ktlint installed will then suddenly change the code.

Please make ktlint-on-formatting at most optional, and make it a regular save action, so that people wanting that behavior can opt-in, but don't make it enforced or even the default.

**Comment by paul-dingemans** [comment]
> This would mean I will immediately uninstall the plugin and recommend everybody to remove it from their IDE, maybe even require to disable it for contributors. That behavior is way too aggressive except if I opted in. 

I do appreciate your feedback. But I would have appreciated, if you had put your critisism in a more constructive and friendly way.

But anyways, you have some valid arguments that I had overlooked. As maintainer of ktlint, I am biased towards always using Ktlint. So, I did not consider working simultaneously on other projects which do not use ktlint. Neither did I realized that installing the plugin also meant that it would run on any project that contains kotlin code. That is something that needed fixing.

After some experimenting, I have now implemented behavior below. Please give me your feedback on it.

When the ktlint plugin is not yet initialized for a project, it ask you to either enable or disabled it. All ktlint violations are highlighted as warnings.
![Screenshot 2023-10-29 at 20 02 57](https://github.com/nbadal/ktlint-intellij-plugin/assets/5195292/81e9caac-e2a2-404d-ae8e-46d157355591)

When enabling it, the Ktlint formatter will be running and violations will be autocorrected (assuming that the project has configured Ktlint in the `.editoconfig` correctly that should be okay for now). Ktlint violations will be highlighted as errors. Actions to suppress the error and to disable ktlint are available on each ktlint violation.
![Screenshot 2023-10-29 at 20 03 30](https://github.com/nbadal/ktlint-intellij-plugin/assets/5195292/94e1c47a-c509-479a-8df2-a496bacb51cb)

Whenever ktlint is disabled, the ktlint violations are highlighted as weak warning. Each violation gives posibility to enable ktlint:
![Screenshot 2023-10-29 at 20 03 56](https://github.com/nbadal/ktlint-intellij-plugin/assets/5195292/bcbf0c18-2f6e-4b7a-9945-64761885a732)

**Comment by Vampire** [comment]
> I do appreciate your feedback. But I would have appreciated, if you had put your critisism in a more constructive and friendly way.

I'm really sorry.
Reading this again, it was really written a "bit" rude, that was not my intention.
It was really just meant as constructive, telling I will stop to use it and why, hoping to achieve a change.
Thanks for mainly skipping over the rude part and considering the constructive part. :-)

> After some experimenting, I have now implemented behavior below. Please give me your feedback on it.

Sounds like a good tactic from a quick look.
It is basically the "do that only if I opted-in for that behavior please" I meant to ask above. :-)
Further feedback I can probably only give after actually trying it.
But it also sounds like a significant improvement, that violations are not rendered as errors anymore unless ktlint is explictily enabled. That allows to jump to other violations in the file that previously were overruled by the error highlighting. :-)

**Comment by Vampire** [comment]
Did you change the logic again @paul-dingemans?
I installed the latest beta version (0.20.0-beta-4) but it seems to not behave as you described.

I see the yellow header saying that ktlint is not configured.
But I neither see warning nor weak warning for violations.

And if I open the "Settings" link the "Enable KtLint" checkbox is checked.
I'd have expected some three-state widget somehow, so that you could also get back to the state where the non-weak warnings are shown, if they were shown at all.

But actually, also disabling or enabling ktlint does not seem to have any effect.

**Comment by Vampire** [comment]
Ah, it is because of an error in the editor config parser, I'll report that separately
