### ISSUE TITLE
Add support for EAP / updated platform versions as they're released

### ISSUE THREAD

**Issue by sureshg** [nbadal/ktlint-intellij-plugin#36]
Plugin stopped working after upgrading to the latest EAP

```
IntelliJ IDEA 2021.1 EAP (Ultimate Edition)
Build #IU-211.4961.30, built on January 26, 2021
Runtime version: 11.0.9.1+11-b1257.1 x86_64
macOS 10.15.7
```

**Comment by nbadal** [comment]
Thanks for the suggestion! I'm working on figuring out a good version support policy – I'll see if there's a way for me to consistently support EAP versions going forward. 😁

**Comment by Gama11** [comment]
Heads-up, 2021.1 is now released.

![image](https://user-images.githubusercontent.com/2620907/113877441-ff6c5b00-97b8-11eb-8db7-ec47a6a89ddf.png)

**Comment by r6e** [comment]
Created #67 to add support for `2021.1`.

**Comment by nbadal** [comment]
Thanks for the heads up all 😄 I'll keep this open to track the creation of a supporting strategy for future versions.

Something that could automatically create a PR like #67 would be amazing, might be automatable too if Jetbrains has a way to subscribe to releases

**Comment by r6e** [comment]
@nbadal Maybe JetBrains' blog RSS feed? This feed seems to include the relevant posts, at least:

```
https://blog.jetbrains.com/idea/category/releases/feed/
```

It looks like it could be filtered by category:

```XML
<category ><![CDATA[releases]]></category>
<category ><![CDATA[intellij-idea-2021-1]]></category>
<category ><![CDATA[newsletter]]></category>
```

The `iintellij-idea-*` can potentially even hint at the new version number. Presuming this feed is stable, anyway.

**Comment by nbadal** [comment]
Just added a nightly action to check for newer releases 🎉

**Comment by Reedyuk** [comment]
Just to add im running 2021.2 RC and the plugin doesnt work, would you be able to release an update to support it?

**Comment by CXwudi** [comment]
> Just to add im running 2021.2 RC and the plugin doesnt support this version(i guess its in the manifest), would you be able to release an update to support it?

Same here, I mentioned it in #109

**Comment by nbadal** [comment]
I appreciate the heads up! I was out of town, but now merging in #110 to address the latest version

**Comment by nbadal** [comment]
It looks like we can include EAP versions in the same script by appending `&release.type=eap%2Crc` to the API call! I'll add that and see how things go

**Comment by nbadal** [comment]
Looks like I still need to fix one bug with the PR script so that it correctly adds the version but at least the PR will be triggered now 😅

**Comment by nbadal** [comment]
Okay, fixed one last bug (`gsed` vs `sed`) but it should be working now! 🤞
