### ISSUE TITLE
Allow plugin to recognize .editorconfig file changes without having to restart the IDE

### ISSUE THREAD

**Issue by StylianosGakis** [nbadal/ktlint-intellij-plugin#367]
Please do correct me if I am wrong here and there is an alternative. But trying out 0.20.0-beta-2 of the plugin, when I do a change in .editorconfig, I still get warnings in the IDE from the ktlint error that I have just supressed. I haven't found a way to force the plugin to re-evaulate the warnings it got with the new editorconfig state other than closing down the IDE and re-opening it.
Closing and reopening the project itself didn't seem to work either.
When I do close the IDE and open it again, the warning goes away correctly.

**Comment by paul-dingemans** [comment]
Tnx for the report. It will be fixed in next beta version.

**Comment by StylianosGakis** [comment]
Thank you for the super quick fix!
