### ISSUE TITLE
Support ktlint 1.0?

### ISSUE THREAD

**Issue by hanqyu** [nbadal/ktlint-intellij-plugin#369]
I wonder this plugin supports for version above 1.0 for ktlint 
https://github.com/pinterest/ktlint/releases/tag/1.0.0

**Comment by paul-dingemans** [comment]
I am working on that. You can use the [beta version](https://github.com/nbadal/ktlint-intellij-plugin/releases/tag/vunspecified) (using ktlint `1.0.1` for now).

**Comment by paul-dingemans** [comment]
Today, ktlint `1.1.0` has been released. You may expect an updated plugin version in a couple of days.

**Comment by paul-dingemans** [comment]
Plugin `0.20.0` has been released using ktlint `1.1.0`.

**Comment by dazza5000** [comment]
Christmas Presents! thank you @paul-dingemans 🍕 🎄 🎁
