### ISSUE TITLE
Lint after reformat setting changes reformat code behavior

### ISSUE THREAD

**Issue by mgoyanes** [nbadal/ktlint-intellij-plugin#37]
If I have the `Lint after reformat` setting enabled when I use the `Reformat Code` option (OPTION+COMMAND+L shortcut on mac) on a block of code, all the file gets reformated.

If I disable the setting,  `Reformat Code` behaves as expected, that is, it only formats the current code block and not the all file.

Ktlint 0.7.1

**Comment by nbadal** [comment]
Unfortunately, ktlint itself isn't capable (currently) of linting a block of code, so the setting is all-or-nothing.
I can add a description in the settings to clarify this though! Sorry for the confusion 😄

**Comment by mgoyanes** [comment]
No problem. Thanks for the explanation.

**Comment by nbadal** [comment]
I'll definitely support partial formats as soon as the tool supports it though! I'll reopen this if that happens

**Comment by mgoyanes** [comment]
Don't know if the tool supports it or not I would prefer the option to apply the specific rule instead of formatting the file and applying all rules.
Example.

![image](https://user-images.githubusercontent.com/5049948/107127151-13283d80-68ac-11eb-9573-1e7ac8b3ab2e.png)

I have two problems there (context actions are for the package). No newline at the end of the file and incorrect order in the imports. 
I would like another context action option. In that case, it would be something like "Add newline to the end of the file". If the context actions were showing for the imports, besides the actual actions, I would like no more: "Sort imports in lexicographic order".

Probably it isn't possible :)
