### ISSUE TITLE
2023.3 compatibility

### ISSUE THREAD

**Issue by Vampire** [nbadal/ktlint-intellij-plugin#376]
I just installed the latest 2023.3 Beta version.
Unfortunately, your plugin is one of three I use that is not declared compatible with it.
Would be great if you could release a compatible version.

**Comment by paul-dingemans** [comment]
I will update the 0.20.0 beta version (using ktlint 1.0.x) coming weekend. Current 0.13.0 version (using ktlint 0.48.x) will not be updated.

**Comment by Vampire** [comment]
Great, thanks. :-)
Is that also released to JetBrains Marketplace, for example on the EAP channel like the Perl plugin is doing: https://plugins.jetbrains.com/plugin/7796-perl/versions/eap ?
Or does one have to build the beta manually?

**Comment by Vampire** [comment]
I also was not, just was told by the Perl plugin guys there is, as their plugin was the second of the three. :-D

**Comment by paul-dingemans** [comment]
Lol, I have just checked and verified that the `0.20.0-beta` versions are compatible with `2023.3`.

**Comment by Vampire** [comment]
Yes indeed, thanks. :-)
