### ISSUE TITLE
Reformatting just a selection

### ISSUE THREAD

**Issue by Vampire** [nbadal/ktlint-intellij-plugin#385]
With 0.20.0-beta-4 when selecting some code block and just invoking a reformat for that block, it would be nice if really just that code block would be reformatted and not the whole file.

I guess ktlint just processes whole files, but maybe the plugin can remember the unselected parts and preserve them or something similar?

**Comment by paul-dingemans** [comment]
This behavior has never been supported by the plugin. I will consider this at a later time.

**Comment by paul-dingemans** [comment]
Reference to #504 is invalid for this issue.

**Comment by Vampire** [comment]
So I got you right that this issue is not yet resolved and should be reopened?

**Comment by paul-dingemans** [comment]
It will be resolved in next release. Unfortunately, I referenced this issue in another PR as well.
