### ISSUE TITLE
Possibility to format manually even if disabled or unconfigured for the current project

### ISSUE THREAD

**Issue by Vampire** [nbadal/ktlint-intellij-plugin#386]
It would be nice if you could manually use the "Format with ktlint" action even if ktlint is not yet configured for the project or even disabled to not get the automatic reformatting.

Currently with 0.20.0-beta-4, if ktlint is disabled or "not yet configured", the "Format with ktlint" action is disabled and cannot be invoked. (Of course besides doing a normal reformat currently due to #380)

**Comment by paul-dingemans** [comment]
You will get more value out of ktlint when the plugin is enabled. But I can see the value of using this path as a way to try-out the plugin. So, after formatting is done and the plugin is not yet enabled, I notify the user with an encouragement to enable the plugin.
