### ISSUE TITLE
Add easy way to undo "disable ktlint"

### ISSUE THREAD

**Issue by nbadal** [nbadal/ktlint-intellij-plugin#39]
If a user accidentally clicks "Disable ktlint", it would be nice to be able to Ctrl+Z or click a button on a popup to quickly cancel.

![image](https://user-images.githubusercontent.com/394812/106955383-0956dc80-66ea-11eb-863a-9b863d61f59c.png)

**Comment by paul-dingemans** [comment]
This option has been removed in the upcoming release.
