### ISSUE TITLE
"formatting complete" notification after "could not parse editorconfig" notification

### ISSUE THREAD

**Issue by Vampire** [nbadal/ktlint-intellij-plugin#398]
With 0.20.0-beta-5, if you have an unparseable editor config like keys without values and trigger a manual ktlint formatting without the plugin being configured, you get three notifications. First a notification that the editorconfig could not be parsed, then that the formatting was complete with a recommendation to enable the plugin fully, then again a notification that the editorconfig could not be parsed.

I'm not so much concerned about twice getting the same parse error even though it feels a bit awkward, but getting a "Formatting is complete" when there was actually an error and no formatting done is just wrong. :-)

**Comment by paul-dingemans** [comment]
Thank you for this really nice challenge. This kind of feedback is very valuable and I appreciate it that you take time to test/use it thoroughly and reporting issues like this.
