### ISSUE TITLE
Support IntelliJ IDEA 2023.3

### ISSUE THREAD

**Issue by SamTheisens** [nbadal/ktlint-intellij-plugin#406]
IntelliJ [IDEA 2023.3](https://www.jetbrains.com/idea/whatsnew/) is out but the latest [stable release](https://github.com/nbadal/ktlint-intellij-plugin/releases/tag/v0.13.0) of the plugin is incompatible.

![Screenshot 2023-12-07 at 11 05 23](https://github.com/nbadal/ktlint-intellij-plugin/assets/1911436/7d77cef3-539d-4dc2-a1f1-d4a901ab9cd5)

**Comment by sanggi-wjg** [comment]
> Working on it. You can use the beta meanwhile https://github.com/nbadal/ktlint-intellij-plugin/releases/tag/0.20.0-beta-5

awsome!

**Comment by nilsschmidthamburg** [comment]
Nice! Thank you. :-)

**Comment by paul-dingemans** [comment]
The new `0.20.0-beta-6` version of the plugin can now be installed via Intellij IDEA marketplace after adding the additional plugin repository `https://plugins.jetbrains.com/plugins/list?pluginId=com.nbadal.ktlint&channel=beta`.

Steps:
* Open plugin page in IntelliJ IDEA
* Go to the gear icon
* Select 'Manage plugin repository'
* Add beta-repository: https://plugins.jetbrains.com/plugins/list?pluginId=com.nbadal.ktlint&channel=beta

**Comment by paul-dingemans** [comment]
Plugin `0.20.0` has been released supporting Intellij IDEA 2023.3.
