### ISSUE TITLE
Highlighting of violations as error/warning

### ISSUE THREAD

**Issue by paul-dingemans** [nbadal/ktlint-intellij-plugin#414]
Given code below:
```
fun foo(a: String, b: String, c: String) =
    a.plus(b)
        .plus(c)

val foo = "longggglongggglongggglongggglongggglongggglongggglongggglongggglongggglongggglongggglongggglongggglongggglongggglongggglongggglongggg"
```

than all ktlint violations are marked as error:
![Screenshot 2023-12-19 at 17 08 09](https://github.com/nbadal/ktlint-intellij-plugin/assets/5195292/0991317a-ed4c-43d4-9ef5-936b711140f5)

In `distract free` mode, after showing all ktlint violations, the errors that can be fixed by ktlint should better be highlighted as warnings. In `manual` mode all ktlint violation should be marked as warning as it is up to the user whether they will be resolved or not.

**Comment by adam-sandor** [comment]
Plus one on this. I'm disabling ktlint until formatting violations are marked the same way as compilation errors. Especially when working on an existing codebase that I don't want to reformat it can be very distracting.

**Comment by paul-dingemans** [comment]
> Plus one on this. I'm disabling ktlint until formatting violations are marked the same way as compilation errors. 

Did you mean that you will wait until they are marked as 'warnings'?

**Comment by adam-sandor** [comment]
Yes marking them as warnings would be fine.
