### ISSUE TITLE
Unable to parse baseline file 😡

### ISSUE THREAD

**Issue by Monabr** [nbadal/ktlint-intellij-plugin#432]
Hello.

After updating to version 0.20.0, all formatting broke. I tried to understand your new settings and I get `Unable to parse baseline file` after I exported it from android studio. What should I do now? 😡😡😡

**Comment by paul-dingemans** [comment]
> What should I do now? 😡😡😡

Start with removing those angry smiles. This is free software, made by volunteers. I am happy to help whenever a request is made respectfully, and with enough information to reproduce the issue. Both are lacking.

**Comment by RahulSDeshpande** [comment]
@Monabr 

If you are facing issues, please uninstall the `ktlint` `0.20.0` plugin from your IDE & rollback it to the previous version.

Please refer this:
https://plugins.jetbrains.com/plugin/15057-ktlint/versions/

@nbadal @paul-dingemans ❤️
