### ISSUE TITLE
Miss matching Function name with @Composable Annotation

### ISSUE THREAD

**Issue by Muhammad-Jafar** [nbadal/ktlint-intellij-plugin#433]
Whenever there is a function anotated with @Composable. Then Ktlint  still detect it as violation of function-naming standard.

Thank you for your atentions

**Comment by paul-dingemans** [comment]
With `0.3.9-SNAPSHOT` version of the compose rules, this problem is fixed in https://github.com/mrmans0n/compose-rules/issues/176. No further action needed in `ktlint-intellij-plugin`.

**Comment by Muhammad-Jafar** [comment]
Thank you so much for your attention.

**Comment by paul-dingemans** [comment]
Problem needs another fix in compose rules. See https://github.com/mrmans0n/compose-rules/issues/190
