### ISSUE TITLE
Can no longer log KTLint issues as Warnings (only errors

### ISSUE THREAD

**Issue by davidstathamimg** [nbadal/ktlint-intellij-plugin#444]
The previous version of the plugin had an option in the settings to 'Annotate ktlint errors as: Warning`

Old Settings:
![old-settings](https://github.com/nbadal/ktlint-intellij-plugin/assets/122885852/299d26f6-a4cc-46c7-bc30-8479b6d14090)

The latest version (0.20.0) has removed this option:

New Settings: 
![new-settings](https://github.com/nbadal/ktlint-intellij-plugin/assets/122885852/99f96685-068b-4140-b76f-d361d2e6d56d)

How can I configure the ktlint plugin to treat ktlint errors as warnings in intellij?

**Comment by paul-dingemans** [comment]
You can not configure this anymore. In next release, #414 is implemented which will display violations as warning in `Manual` mode.
