### ISSUE TITLE
Intellij plugin 0.20.1 is put under beta in jetbrains website

### ISSUE THREAD

**Issue by davidcorradowell** [nbadal/ktlint-intellij-plugin#457]
https://plugins.jetbrains.com/plugin/15057-ktlint/versions/beta/475170
<img width="1038" alt="Screenshot 2024-01-26 at 2 53 12 PM" src="https://github.com/nbadal/ktlint-intellij-plugin/assets/145368636/7bbf2cf2-a67e-488a-bbd5-45cbf7d10d79">

**Comment by paul-dingemans** [comment]
It is also submitted to the stable channel, but not yet approved by Jetbrains. It was an explicit request to also publish the stable versions on the beta channel.

**Comment by davidcorradowell** [comment]
Makes sense.  Thanks for clarification
