### ISSUE TITLE
Plugin marked as incompatible with IJ 24.1 EAP

### ISSUE THREAD

**Issue by rock3r** [nbadal/ktlint-intellij-plugin#463]
Hi, would it be possible to bump the max supported version to include 241.*? Thanks!

PS: the only gotchas I can think of are that all actions must declare their threading, and configurables must have a label. If those are done, then the rest is likely to work as-is. I'll be happy to file bugs if I encounter any issues.

**Comment by paul-dingemans** [comment]
For EAP versions of intellij please add Plugin Repository https://plugins.jetbrains.com/plugins/list?pluginId=com.nbadal.ktlint&channel=beta to your plugin settings.
