### ISSUE TITLE
Setting not maintained after Android Studio restart.

### ISSUE THREAD

**Issue by mgoyanes** [nbadal/ktlint-intellij-plugin#47]
If I disable the setting **Lint after Reformat**, if I restart Android Studio, the setting becomes automatically enabled.
Was expecting that the setting value was maintained after restarts.

**Comment by nbadal** [comment]
Good catch! Fixed, and will push an update soon 😄

**Comment by mgoyanes** [comment]
> Good catch! Fixed, and will push an update soon 😄

Great. Thanks.
