### ISSUE TITLE
Change ktlint errors in IDE to warning level

### ISSUE THREAD

**Issue by 14v** [nbadal/ktlint-intellij-plugin#473]
After installing plugin got ktlint errors underlined red. This is mixed with compilation errors. How can I change ktlint error level to warning (yellow) ?

**Comment by paul-dingemans** [comment]
Please include code sample and screendump.

**Comment by 14v** [comment]
For example use star import when it is prohibited

![image](https://github.com/nbadal/ktlint-intellij-plugin/assets/4716175/1fa55730-9ff6-4d64-9630-96d9da618a40)

**Comment by paul-dingemans** [comment]
This is normal behavior. Error level can not be changed manually anymore. If you don't care about wildcard imports, it is better to disable the rule. https://pinterest.github.io/ktlint/latest/faq/#how-do-i-enable-or-disable-a-rule
