### ISSUE TITLE
Still get max line length error after upgrade to 0.21

### ISSUE THREAD

**Issue by XhstormR** [nbadal/ktlint-intellij-plugin#483]
Plugin 0.21 runs with ktlint version 1.2.1. According to this PR, we should be fine with only one line of string. 
https://github.com/pinterest/ktlint/pull/2480
![image](https://github.com/nbadal/ktlint-intellij-plugin/assets/10527522/61755f0d-cad0-4482-8147-f04b11abde8a)
![image](https://github.com/nbadal/ktlint-intellij-plugin/assets/10527522/4030780f-bcaa-42e0-a252-3cd002fe00b0)

**Comment by paul-dingemans** [comment]
Most likely your string is followed by a trailing comma. See new issue [A line only containing a string and a trailing comma should not be reported to exceed max line length](https://github.com/pinterest/ktlint/issues/2597).

**Comment by XhstormR** [comment]
> Most likely your string is followed by a trailing comma. See new issue [A line only containing a string and a trailing comma should not be reported to exceed max line length](https://github.com/pinterest/ktlint/issues/2597).

Yes, followed by a trailing comma.
