### ISSUE TITLE
Miss matching Function name with @Composable Annotation 

### ISSUE THREAD

**Issue by ashrafatef843** [nbadal/ktlint-intellij-plugin#495]
[Compose rules](https://github.com/mrmans0n/compose-rules) doesn't work inside the plugin.

Compose rule version jar: [v0.3.13](https://github.com/mrmans0n/compose-rules/releases/tag/v0.3.13)
Android studio version: Android Studio Hedgehog | 2023.1.1
Ktlint plugin version: 0.21.0

```
@Composable
fun TestCompose() {
}
```

Error:
Function name should start with a lowercase letter (except factory methods) and use camel case (standard:function-naming)

.editorconfig:
```
root = true

[*]
insert_final_newline = false
max_line_length = 100

[{*.kt,*.kts}]
ij_kotlin_allow_trailing_comma = true
ij_kotlin_allow_trailing_comma_on_call_site = true
ij_continuation_indent_size = 4
```

**Comment by paul-dingemans** [comment]
Did you configure this correctly in your `.editorconfig`? See https://pinterest.github.io/ktlint/latest/rules/standard/#function-naming

**Comment by ashrafatef843** [comment]
@paul-dingemans No I just downloaded the [jar file](https://github.com/mrmans0n/compose-rules/releases/tag/v0.3.13) of ktlint and added it to the plugin inside the field of Ruleset Jars.

![image](https://github.com/nbadal/ktlint-intellij-plugin/assets/142246847/1b4238f5-1749-490a-872c-298d166db6f5)

**Comment by paul-dingemans** [comment]
That is not enough. You need to configure to avoid conflict with ktlint rules. See ktlint documentation link above.
