### ISSUE TITLE
IDEA 2024.1 unsupported

### ISSUE THREAD

**Issue by JoonasC** [nbadal/ktlint-intellij-plugin#497]
Not sure if this is a bug on Jetbrains' side, but all plugin versions are marked as not supporting IDEA 2024.1
![image](https://github.com/nbadal/ktlint-intellij-plugin/assets/3898724/41258b51-1bd6-49dd-aec9-f58c9f4d71c8)

**Comment by paul-dingemans** [comment]
Sorry for the inconvenience. Im still looking into optimizing my workflow with the Intellij IDEA release cadance. And, apparently it needs some more work.

I will update this week.

**Comment by JoonasC** [comment]
No problem, thank you for maintaining this project

**Comment by paul-dingemans** [comment]
New plugin version is approved by Jetbrains and should be available via Jetbrains Marketplace.
