### ISSUE TITLE
What are the ktlint --disabled_rules?

### ISSUE THREAD

**Issue by ericR-123** [nbadal/ktlint-intellij-plugin#5]

**Comment by nbadal** [comment]
If I'm misunderstand your question let me know! But you can find **ktlint**'s rule names in the error message if you hover over the error annotation like this one for `no-semi`:

<img width="362" alt="Screen Shot 2020-10-17 at 1 41 33 PM" src="https://user-images.githubusercontent.com/394812/96353158-7a607e80-107e-11eb-884c-3027a10632db.png">

I'll also be adding an option to disable the rule via the fix list as well 😄

**Comment by nbadal** [comment]
I can also see about adding some autocomplete to this field as well, that would probably be helpful!

**Comment by nbadal** [comment]
@ericR-123 adding both of these features to v0.4.0 😁 closing for now
