### ISSUE TITLE
Add option to run ktlint only when running Reformat Code (Ctrl+Alt+L)

### ISSUE THREAD

**Issue by vitiasr** [nbadal/ktlint-intellij-plugin#519]
Assume the following case:

<img width="184" alt="image" src="https://github.com/nbadal/ktlint-intellij-plugin/assets/37491331/ad5409ba-63a7-4334-8daa-b46791bfbc68">

After selecting the variable name, as shown above, when I click the left curly bracket key on my keyboard, the variable name is not wrapped in curly brackets as expected, because ktlint is being fired automatically and removes them instantly.

It would be nice to have an option to run ktlint **_only_** when using Reformat Code (Ctrl+Alt+L).

**Comment by paul-dingemans** [comment]
If you disable option 'format on save' this should work as you expect.

**Comment by vitiasr** [comment]
Unfortunately it does not. The only option I have right now is to disable the Distract Free mode altogether.

**Comment by paul-dingemans** [comment]
Just checked it, and the `format on save` is not related to this. 

I can reproduce the behavior you described. Unfortunately, I can not find a solution for this as you want to run Ktlint formatting together with (e.g. after) formatting of Intellij IDEA. For some reason the `PostFormatterProcessor` hook gets fired once you insert the left curly brace manually.

Interestingly enough, if you use option `insert curly braces around variable` the`PostFormatterProcessor` does not get triggered, and you get the behavior you want. 

As, this is not something that I can fix in the plugin, I will close the issue.
