### ISSUE TITLE
Compatibility with composable function names

### ISSUE THREAD

**Issue by ellet0** [nbadal/ktlint-intellij-plugin#524]
First of all, I would like to thank you for your efforts on this project.

Currently, if you are using [Compose multiplatform](https://www.jetbrains.com/lp/compose-multiplatform/) or [Compose Desktop](https://github.com/JetBrains/compose-multiplatform-desktop-template) or any project that use `Composable` functions, by default it will be against the naming conventions and [IntelliJ IDEA](https://www.jetbrains.com/idea/) will suggest to rename the function, this can be fixed by using [Android Studio](https://developer.android.com/studio) or installing [Compose Multipaltform IntelliJ IDEA plugin](https://plugins.jetbrains.com/plugin/16541-compose-multiplatform-ide-support), but when using [Ktlint IntelliJ IDEA plugin](https://plugins.jetbrains.com/plugin/15057-ktlint) it would give the following warning:

![image](https://github.com/nbadal/ktlint-intellij-plugin/assets/73608287/92190949-e43e-4519-9c84-7c545bf2b0d2)

Which can be ignored using:
```kotlin
@Suppress("ktlint:standard:function-naming")
@Composable
fun App() {}
```

Or add it to each Gradle Module that uses Compose or to the whole project if all the modules use Compose Desktop, I'm not sure how but is it possible to support Compose projects? I haven't tried out KtLint IntelliJ IDEA plugin with Android Studio so maybe it already has this feature by default

Thank you once again.

**Comment by paul-dingemans** [comment]
Please see ktlint documentation for configuring this rule: https://pinterest.github.io/ktlint/latest/rules/standard/#function-naming

**Comment by ellet0** [comment]
> Please see ktlint documentation for configuring this rule: https://pinterest.github.io/ktlint/latest/rules/standard/#function-naming

Thank you, I'm not sure but if there is a way to detect if this a compose project or maybe Compose Desktop IDE plugin installed then it will be used or added automatically

**Comment by paul-dingemans** [comment]
In next version of the plugin, I have already changed the preference screen slightly to mention Jetpack Compose as a popular ruleset.
<img width="986" alt="Screenshot 2024-05-21 at 18 58 38" src="https://github.com/nbadal/ktlint-intellij-plugin/assets/5195292/02b9f907-3eb7-46f7-88b9-7e330afaf70b">

Technically, it is possible to scan all kotlin files for the existence of an import for a Compose package. If so, and the Jetpack Compose ruleset is not used, the plugin could than  emit a message like "It looks that you are using Compose. Do you know that a Jetpack Compose ruleset for ktlint exists?". But the user will still need to download the Jetpack Compose ruleset, and configure it manually. The intellij plugin will never be able to install the Jetpack Compose ruleset automatically, as I do not want the project to be dependend on external projects (other than ktlint of course).

**Comment by ellet0** [comment]
It could ignore the message without using the lint but then this will only work on the IntelliJ IDEA Plugin and not using the KtLint command
