### ISSUE TITLE
Compose functions naming warning

### ISSUE THREAD

**Issue by lydian9817** [nbadal/ktlint-intellij-plugin#531]
Hi, I'm encountering an issue while using Compose. Compose functions start with An uppercase letter, and I find it a bit unclean to suppress the warnings on every composable.
Thanks in advance!

![image](https://github.com/nbadal/ktlint-intellij-plugin/assets/106270317/90ba0342-57b1-43c3-a24c-cd226cd1a8cf)

**Comment by paul-dingemans** [comment]
This can be configured in `.editorconfig`. See https://pinterest.github.io/ktlint/latest/rules/standard/#function-naming
