### ISSUE TITLE
With the new update, different KtLint rules are being applied.

### ISSUE THREAD

**Issue by SrBrahma** [nbadal/ktlint-intellij-plugin#537]
Maybe it's no longer using my .editorconfig and is now using the default rules?

**Comment by SrBrahma** [comment]
https://github.com/nbadal/ktlint-intellij-plugin/issues/536

**Comment by SrBrahma** [comment]
I thought the linked issue was related to this but it isn't.

**Comment by SrBrahma** [comment]
Found the issue: The plugin uses the last Ktlint version, while my project uses 1.1.0. The 1.3.0 moved some rules from experimental to non-experimental, that's why they are now being applied

**Comment by paul-dingemans** [comment]
> Found the issue: The plugin uses the last Ktlint version, while my project uses 1.1.0. The 1.3.0 moved some rules from experimental to non-experimental, that's why they are now being applied

Starting from version `0.23.0` the plugin allows you to run with an older version like `1.1.0` if you don't want or cannot update the ktlint version in the project. See Ktlint Plugin preferences.

**Comment by SrBrahma** [comment]
Ty! 🤗
