### ISSUE TITLE
Copy-paste error in "Lint after Reformat" tooltip

### ISSUE THREAD

**Issue by Gama11** [nbadal/ktlint-intellij-plugin#54]
The checkbox has the same tooltip as the one above it, which is likely a copy-paste error:

![image](https://user-images.githubusercontent.com/2620907/110455063-4424a980-80c8-11eb-9f9e-a96c72a40ffc.png)

**Comment by nbadal** [comment]
Good catch! The disabled rules field is also missing a tooltip 😄  Fix incoming

**Comment by nbadal** [comment]
Fixed for next release!
