### ISSUE TITLE
Configure `Ruleset version` for Plugin  via `.editorconfig` file

### ISSUE THREAD

**Issue by ievgen-kapinos** [nbadal/ktlint-intellij-plugin#540]
Hi

On our projects my team uses `ktlint-intellij-plugin` (dev environment) and [jlleitschuh/ktlint-gradle](https://github.com/jlleitschuh/ktlint-gradle) plugin (rarely on dev environment, always on CI/CD server). 

In this Gradle plugin we can set `ktlint version` as described [here](https://github.com/jlleitschuh/ktlint-gradle?tab=readme-ov-file#configuration). That works well, because we can store it in repository and it will be applied automatically in all dev environments and CI/CD.

As for `ktlint-intellij-plugin` I have to manually set `ktlint version` via IDE settings in each project. This problem becomes more painful when we have many developers using same project. Also, different projects may use different `ktlint version`. 

**Could you consider to add an option to fetch Ruleset version (`ktlint version`) from `.editorconfig` file?**

I suppose it should be some new custom setting specifically prefixed for your plugin (like Idea has own settings with prefix `ij_`). So it can be stored in a repo and automatically applied in all dev environments where `ktlint-intellij-plugin` is installed. If setting is not found, then default behaviour can be used. I suppose now your plugin by default uses some hardcoded `ktlint version`. In UI it appears as `Ruleset version: default (recommended)`. 

Something like this
![Screenshot 2024-06-20 at 16 13 15](https://github.com/nbadal/ktlint-intellij-plugin/assets/3447597/b2c40777-e048-4cca-ab9f-c276908cc4e5)

P.S. It is clear that fetching `ktlint version` from `jlleitschuh/ktlint-gradle` plugin has no sense.

**Comment by paul-dingemans** [comment]
> Could you consider to add an option to fetch Ruleset version (`ktlint version`) from `.editorconfig` file?

Please commit file `.idea/ktlint-plugin.xml` to your version control. In this way, all preferences of the plugin will be shared amongst all developers on the project.

**Comment by ievgen-kapinos** [comment]
Need to try. Thank for the idea.

**Comment by ievgen-kapinos** [comment]
@paul-dingemans thank you for quick respond. 

It works. Also I've discovered Idea feature [Required Plugins](https://www.jetbrains.com/help/idea/managing-plugins.html#required-plugins). So Idea IDE can notify user, if plugin is not installed.

Here what I end up (notes for those who what to implement the same):

`.gitignore`
```
.idea/*
!.idea/externalDependencies.xml
!.idea/ktlint-plugin.xml
```

`.idea/externalDependencies.xml` - configured via UI. 
```
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="ExternalDependencies">
    <plugin id="com.nbadal.ktlint" />
  </component>
</project>
```

`!.idea/ktlint-plugin.xml` - configured via UI. 
```
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="KtLint plugin">
    <ktlintMode>MANUAL</ktlintMode>
    <ktlintRulesetVersion>V1_0_1</ktlintRulesetVersion>
  </component>
</project>
```

Keep in mind, files in `.idea` foldet not updated immediately (click `OK` or `Apply` in Settings), but only after IDE quit.

**Comment by paul-dingemans** [comment]
Tnx for sharing back the [required plugin](https://www.jetbrains.com/help/idea/managing-plugins.html#required-plugins) settings which indeed might be helpful in cases like you describe. As you now have a working solution, I will close the issue.
