### ISSUE TITLE
Disable inspections while also having "Lint after Reformat" active

### ISSUE THREAD

**Issue by Gama11** [nbadal/ktlint-intellij-plugin#55]
Personally I don't like ktlint violations showing up as inspections (with a highlighted background etc), it can be rather distracting, especially with big multi-line ranges being highlighted. As far as I can tell, "Disable ktlint", which disables this, also disables everything else. However, I still want to have "Lint after Reformat" enabled.

My use case is basically just "format on save" - I have "Reformat Code" assigned to Ctrl+S which I press every so often while writing code to fix the formatting. That allows me to write code without being distracted by getting the formatting details right manually. Well, unless those formatting issues distract me via inspections. :)

So far I've been using the IntelliJ formatter config generated by ktlint, but unfortunately there's some edge cases where `ktlint -F` and the IntelliJ formatter behave differently, so this plugin seems to be exactly what I'm looking for.

**Comment by nbadal** [comment]
Glad to hear that the plugin is providing value to you! Maybe a good solution could be a dropdown where the user can select a severity level, or "None" in your case? 😃

**Comment by Gama11** [comment]
Sure, that sounds like it should do the trick. 👍

**Comment by nbadal** [comment]
Consider it done! It will be out with the next release sometime around this weekend 🤞

**Comment by Gama11** [comment]
Just tested the new release, seems to work great. :)
