### ISSUE TITLE
[Request] Manual option without code warning

### ISSUE THREAD

**Issue by fillipeoliveira-hotmart** [nbadal/ktlint-intellij-plugin#550]
Hi, Nice plugin.

Is possible to add a option to when set manual, not show the erros/warning on Code?
I like the format only when press the key but all the warnings on code drive me nuts.. LOL

Thx!

**Comment by paul-dingemans** [comment]
> all the warnings on code drive me nuts.. LOL

Yeah, this was one of the main reasons for adding the 'distract free' mode.

> Is possible to add a option to when set manual, not show the erros/warning on Code?

Technical that is feasible. UX wise I don't like it.

What are you reasons for using the 'manual' mode?

**Comment by paul-dingemans** [comment]
So you want to use the plugin to format your code with ktlint only when you explicitly invoke "Format with ktlint". At no other moment you want to be bothered by notifications, lint warnings, nor automatic formatting. The plugin might not be the best option for you then. I would recommend Ktlint CLI in that case.

**Comment by fillipeoliveira-hotmart** [comment]
yes, sort of..
Just override the "Reformat Code" of the IDE with the format of the ktlint plugin like the manual but without the lint warnings on code.

> The plugin might not be the best option for you then. I would recommend Ktlint CLI in that case.

That's sad, but thanks for your help. =)

**Comment by paul-dingemans** [comment]
> yes, sort of.. Just override the "Reformat Code" of the IDE with the format of the ktlint plugin like the manual but without the lint warnings on code.
> 
> > The plugin might not be the best option for you then. I would recommend Ktlint CLI in that case.
> 
> That's sad, but thanks for your help. =)

Can you try whether "Distract Free" combined with disabling "on save" is what you are looking for? "Distract free" ensures that you only 1 warning containing the number of lint violations that is found by Ktlint. When "on save" is disabled, no formatting is happening automatically when the file is save (which is quite often).
