### ISSUE TITLE
Don't show editor banner when plugin is not explicitly enabled

### ISSUE THREAD

**Issue by rock3r** [nbadal/ktlint-intellij-plugin#553]
If you open a project where ktlint is not set up, and the ktlint plugin is not explicitly enabled either:

<img width="689" alt="image" src="https://github.com/user-attachments/assets/0de9f31c-2be3-4737-aded-b4c25496aa9c">

I should not see the ktlint banner in the editor:

<img width="1841" alt="image" src="https://github.com/user-attachments/assets/c992f510-5507-4f5b-a9bd-26d126c353a4">

**Comment by paul-dingemans** [comment]
The banner is shown intentionally, until you make an explicit choice whether ktlint should or should not run for this project.

**Comment by rock3r** [comment]
It is incredibly annoying. Can't you come up with a less disruptive way to ask the user what they want to do? For example a notification when you open a project the plugin is not configured for.

**Comment by rock3r** [comment]
Adding to that - explicitly disabling the plugin writes a file to the project folder, which may show up in VCS. That's probably not something you want to impose on your users — the choice of an always on annoyance (the banner) or having a file you need to commit to VCS to opt out from using a plugin the project doesn't need.
