### ISSUE TITLE
Ktlint plugin should assume to be disabled by default

### ISSUE THREAD

**Issue by rock3r** [nbadal/ktlint-intellij-plugin#554]
When not explicitly enabled, the plugin should consider itself to be disabled by default. Not all projects I open use/want ktlint, and it's very annoying to have the ktlint plugin thinking it's enabled by default on all projects (see #553 as one of the side effects).

**Comment by paul-dingemans** [comment]
If you have installed the ktlint plugin, you need to make a choice whether the plugin should or should not run for the project. When starting or importing a new project this is a convenient way to remind the user about configuring ktlint for the project. You may find it annoying, for others it is a welcomed feature.

**Comment by rock3r** [comment]
I love ktlint and appreciate the value the plugin brings to the table in the codebase where ktlint is used. However, it is an actively annoying "feature" when you work on a mix of projects that use and don't use ktlint.

> You need to make a choice whether the plugin should or should not run for the project

I understand where you're coming from, but I'm sure you can realise this scenario only really works if you use ktlint in all your projects. For people like me who don't, because they often work across codebases owned by different teams and orgs, each with their policies, this behaviour is unsatisfactory.
