### ISSUE TITLE
Editor notification "Ktlint found ... lint violations.." shown in every project

### ISSUE THREAD

**Issue by jansorg** [nbadal/ktlint-intellij-plugin#555]
I installed the Ktlin plugin because ktlint is used in one project. It's not used in the other projects.
Now in every kotlin file of every other project there's an editor notification panel saying "Ktlint found ... lint violations...".
This doesn't seem to be from an inspection, so I can't disable this notification. 

I know that I can turn this off via "Disabled" in the Ktlin settings. But this creates a ktlint project settings file, which I don't need or want.
I'd really prefer if it wasn't enabled for every project by default when it's not possible to suppress the notification.

You could: 
- add an application-level settings
- or use a supressable inspection to add the editor notification
- or change the default to "Disabled" for the project settings
- or only show the notification when the user made a choice in the ktlint settings.

**Comment by paul-dingemans** [comment]
> I'd really prefer if it wasn't enabled for every project by default when it's not possible to suppress the notification.

I appreciate the careful wording and suggestion below:

> add an application-level settings

I can add a application-level setting like "Show banner when plugin is not initialized in project" which is enabled by default.

**Comment by jansorg** [comment]
Thanks! This would make it a setting I'd have to change only once.
