### ISSUE TITLE
.editorconfig with empty values like from IntelliJ export breaks parsing (a.k.a. please update ktlint)

### ISSUE THREAD

**Issue by Vampire** [nbadal/ktlint-intellij-plugin#575]
As a follow-up to pinterest/ktlint#2824, please release a new version of this plugin with a new ktlint version with the fix for that issue, so that empty values in editorconfig files do not cause a parse error.

Especially with IntelliJ this is important, as an `.editorconfig` file that was made by exporting IntelliJ settings most probably contains such empty values.

**Comment by paul-dingemans** [comment]
The plugin is typically released within a week after release of new ktlint version.

**Comment by Vampire** [comment]
Sooo, two weeks have passed since the ktlint release ... :-)

**Comment by paul-dingemans** [comment]
Yes that is why I used the word "typical". The beta version is updated but has a problem which I have not yet resolved.

**Comment by Vampire** [comment]
Unfortunately not.
I upgraded the plugin but I still get 
> Caused by: java.lang.AssertionError: An error occurred while reading the '.editorconfig':
> path:/Sourcecode/project/.editorconfig:17:19: Property 'ij_visual_guides' has no value

That the drive letter is missing in the path is also a sign still the old ktlint is used, as this was fixed.
:-(

**Comment by Vampire** [comment]
I even tried to completely uninstall the plugin, verified the files were gone and then reinstalled the plugin, same situation

**Comment by Vampire** [comment]
Did you see my comments @paul-dingemans? :-)

**Comment by paul-dingemans** [comment]
See new issue #598. I have tried to resolve this, but I am not able too due to lack of enough experience with the shadow plugin and/or gradle.
