### ISSUE TITLE
Add option to disable plugin by default

### ISSUE THREAD

**Issue by matejdro** [nbadal/ktlint-intellij-plugin#586]
Currently plugin seems to be enabled by default on all projects and has to be explicitly disabled on projects that do not use ktlint.

Could we add an option to disable it by default and then only explicitly enable it on projects that use ktlint?

**Comment by paul-dingemans** [comment]
This already exixts. See setting `show banner when plugin is not initialized in project`.

![Screenshot 2024-10-24 at 12 05 48](https://github.com/user-attachments/assets/9a1df5d4-6943-4dd5-8956-4e2868c6b0a9)

**Comment by matejdro** [comment]
I don't see that option in my IDE:

![image](https://github.com/user-attachments/assets/dcac311a-9243-49c9-a3f9-2e413f0bdc6c)

running ktlint 0.24.1 in Android Studio Ladybug.

**Comment by paul-dingemans** [comment]
Sorry, I didn't realize how new this option is. It is available in the beta version though.
