### ISSUE TITLE
Plugin does not support K2 mode?

### ISSUE THREAD

**Issue by fgeck** [nbadal/ktlint-intellij-plugin#589]
I can see that in the [xml k2support](https://github.com/nbadal/ktlint-intellij-plugin/blob/77cc5db415d688a274cdaa6cc9a5cfe463b5776d/plugin/src/main/resources/META-INF/plugin.xml#L22) is true, but somehow my intellij runs into errors saying the plugin is incompatible.

Is the error on my side, or on the plugin side? And does someone maybe know how to fix it?

Intellij version: `IntelliJ IDEA 2024.2.4 (Ultimate Edition) --- Build #IU-242.23726.103, built on October 23, 2024`
ktlint plugin version: `0.24.1`

```log
2024-10-28 10:28:52,813 [334099337]   INFO - #c.i.i.p.DynamicPlugins - Plugin com.nbadal.ktlint depends on the Kotlin plugin in K2 Mode, but the plugin does not support K2 Mode

2024-10-28 10:29:12,929 [    336]   WARN - #c.i.i.p.PluginManager - Problems found loading plugins:
  The Ktlint (id=com.nbadal.ktlint, path=~/Library/Application Support/JetBrains/IntelliJIdea2024.2/plugins/ktlint, version=0.24.1) plugin Plugin 'Ktlint' wasn't loaded because it's incompatible with the Kotlin plugin in "K2" mode
```

![Screenshot 2024-10-28 at 10 53 16 AM](https://github.com/user-attachments/assets/e94a2ed2-0921-4957-9fae-3426b79da79f)

**Comment by paul-dingemans** [comment]
What version of the plugin are you using? K2 mode is currently supported in the 0.25.0-beta versions only.

**Comment by paul-dingemans** [comment]
Just in the Idea plugin screen:
![Screenshot 2024-10-28 at 17 29 34](https://github.com/user-attachments/assets/14cb4517-4c3b-43cc-bc2a-e49ecf1cbbf3)

**Comment by fgeck** [comment]
ah you meant ktlint plugin version.
This is version: `0.24.1`

<img width="468" alt="image" src="https://github.com/user-attachments/assets/7d5d0c70-c2ae-4650-a855-51348b3d7538">

**Comment by paul-dingemans** [comment]
0.25.0 is already available as beta. Official release follows in a couple of days

**Comment by wallind** [comment]
[`0.25.0`](https://github.com/nbadal/ktlint-intellij-plugin/releases/tag/0.25.0) is released and available in IntelliJ, and I can confirm it fixes the issue!

Thanks for fixing this, our team loves this plugin and relies on it heavily for our linting solutioning.
