### ISSUE TITLE
Add option to resolve the ktlint version from the current project

### ISSUE THREAD

**Issue by sondrele** [nbadal/ktlint-intellij-plugin#592]
It would be nice if the plugin could pick up the ktlint version from the list of dependencies of currently opened kotlin project instead of having to specify the ktlint version explicitly (or the default latest).

### Why? 

It would make it possible to control the ktlint version for a project independent of which version of the plugin that I (and my team mates) have installed in Intellij.

### More background

I have a kotlin + gradle project. I have configured the project with [gradle a plugin](https://github.com/JLLeitschuh/ktlint-gradle) that can verify that the sources are formatted correctly. This plugin has been configured to resolve the ktlint-cli from the project dependencies (specified in `gradle/libs.versions.toml`) instead of whatever version it gets bundled with and it runs on the CI server.
In addition, I'm using the ktlint-intellij-plugin because it makes it easier to format the code while developing (thanks for the plugin btw!).

However, for new relases of ktlint (usually major or minor) we have to wait for this plugin also release a new version, otherwise we end up in a state where the the ktlint-version of the project is not in sync with the ktlint-version of the intellij plugin.

If this plugin could also resolve the ktlint version from the classpath of the currently opened project it would integrate nicely with other tools, like e.g. dependabot for automatic version updates etc.

**Comment by paul-dingemans** [comment]
Duplicates #540 

There are many different integrations with ktlint. Some of them allow the user to configure the 
ktlint version to their liking. The way this is done can vary wildly. The plugin would need to know about all those different kind of integrations to determine how it should determine the ktlint version that is configured by that integration.

With the idea of #540 you can make it easy for co-workers on the project to keep using the correct ktlint version.
