### ISSUE TITLE
Minimal Ktlint actions for IdeaVim

### ISSUE THREAD

**Issue by davidarmstronglewis** [nbadal/ktlint-intellij-plugin#74]
I use IdeaVim and tend to hook up formatting actions to keystrokes. Running `:actionlist` using IdeaVim shows me that there aren't any actions available to bind. Would it be possible to present some to users so that we can do stuff like the following?

```vim
" binds ctrl+shift+i to the action `KtlistFormatFile`
nnoremap <C-S-i> :action KtlintFormatFile<CR>
```

Great idea for a plugin, thank you! Gonna try to incorporate it into my workflow 😄

**Comment by nbadal** [comment]
Great idea! I'll take a look at how IdeaVim searches for actions 😁

**Comment by nbadal** [comment]
So until this point, all the "actions" available were intention actions, which are separate from standard actions. I've added a format action under the `Reformat` menu. It now shows up under `:actionlist`, and I think it should allow keybinding in general too :) 

![image](https://user-images.githubusercontent.com/394812/116489964-113a9e80-a84b-11eb-89ea-e190ff75da57.png)

**Comment by davidarmstronglewis** [comment]
Woot! Thank you! 🙌
