### ISSUE TITLE
Suggestion: Run ktlint analysis on demand

### ISSUE THREAD

**Issue by mgoyanes** [nbadal/ktlint-intellij-plugin#75]
When opening a file, the plugin immediately checks the file. Also, in some situations, I can see that, while changing the file, the checks are stopped and I need to close and reopen the file to force the checks to run again (sometimes this even fails).

As a user, I would like to have:

1. Have an option to force the ktlint checks on the file. For example, an action with the name "Run ktlint checks on file" will force the checks on the current file. It does not format, it will just check and if any issue found, show them as warnings/error/none accordingly to the setting.
2. Have a checkbox in settings (just like "Enable ktlint") with "Only perform checks on demand". When that setting is enabled, opening a file does not automatically trigger the ktlint checks. If we want to check we will make use of point 1 above.

P.S. - You added "Format With ktlint" to the refactor menu but it's missing when we use the shortcut for "Refactor this".

![image](https://user-images.githubusercontent.com/5049948/116779946-298c0280-aa71-11eb-8d51-22cf2b7fd011.png)

**Comment by nbadal** [comment]
Interesting! I'll dig in and see how feasible this is with the available Annotations API. 
So far, this plugin doesn't manage anything to do with triggering annotations checks, but there might be a way to temporarily enable a check 🤔 

One thing I've been looking into is adding support for is lint rules as `Inspections` which would allow on-demand analysis. Would that be a decent solution for your use case?

**Comment by mgoyanes** [comment]
> One thing I've been looking into is adding support for is lint rules as `Inspections` which would allow on-demand analysis. Would that be a decent solution for your use case?

Sorry. Don't know how that works

**Comment by paul-dingemans** [comment]
In upcoming release of the plugin, the behavior of the plug will be even more standardised. Like Ktlint, the plugin should help the developers to become more productive. Manual fixing of errors is a waste of time (given that you have configured ktlint to your liking). So format runs automatically and can not be disabled.
