### ISSUE TITLE
Add mechanism to disable rule for all projects

### ISSUE THREAD

**Issue by huehnerlady** [nbadal/ktlint-intellij-plugin#77]
Hi,

I like the plugin a lot, what I am missing is an option, to have a few rules disabled not on a project-level, but for all projects together. I would see it as kind of a hierarchy, that you have the rules that are disabled for all projects, and then you have the rules that are disabled for one particular project

**Comment by nbadal** [comment]
Hello! I'm glad you're enjoying the plugin 😄 

I'll give this suggestion some thought – I'm wary of adding functionality that isn't a part of `ktlint` by itself, because I want to maintain parity between command-line usage and IDE usage.

Maybe I can open a PR on ktlint to add a `~/.global_ktlint` configuration of sorts 😅

**Comment by huehnerlady** [comment]
I see your point. I would say as it is a commandline you could have 2 boxes, one for the project and one that is global. Then you could combine the 2 in the command line. But I do like your idea with having a global ktlint file. I guess you could add more functionality to that than just disabling rules as well, if there are any that would make sense :)

**Comment by paul-dingemans** [comment]
The plugin should not support this. I think it is an essential part of the project configuration to know which rules are disabled/enabled and as of that this information needs to be stored in the `.editorconfig` file (and it should be stored in VCS as well). If you really want to achieve something like this, then it is possible with `.editorconfig` files. When you omit property `root = true` from the `.editorconfig` file, then the parent directories are scanned until an `.editorconfig` is found in which this property is set. For this you need to create an `.editorconfig` at a higher level than your project directories.
